### ISSUE TITLE
test models

### ISSUE THREAD

**Issue by ZF1546** [solitaire2015/Split_Merge_table_recognition#1]
hi, I want to test ,but I can't find the test models ,where can I get it?
thanks very much

**Comment by ZF1546** [comment]
@solitaire2015pre-trained models or final models,if it's convenient for you.
I have clone  the test script,but I can't run  test.py ,because no models to load in Specified path.
thanks very much!!

**Comment by solitaire2015** [comment]
I uploaded two model checkpoints trained on my private dataset, it's may not perform well your dataset.
Merge: https://pan.baidu.com/s/112ElDK-MSMQ50CTKpkPCZQ    code:rto4
Split: https://pan.baidu.com/s/1rSO6o23WbKV6jXo2DRrQcw  code:lu23

**Comment by ZF1546** [comment]
@solitaire2015 
ok,thanks very much!
