### ISSUE TITLE
数据集制作

### ISSUE THREAD

**Issue by ZF1546** [solitaire2015/Split_Merge_table_recognition#2]
你好！我在用自己制作的数据集训练模型，但是一直有问题，可以分享一下你的数据集制作方法吗，谢谢！

**Comment by solitaire2015** [comment]
@ZF1546 你好，我们的数据集的标注方法是在原图上对于每条线，用个紧贴线的矩形框表示，并且标记线是横线还是竖线，根据标注的所有线可以画一个mask出来，对mask求连通域，每个连通域就是一个表格了，可以根据横线求表格在整图中的角度，然后求每个连通域在这个角度下的最小包裹矩形，然后把这个矩形块切出来，从原图上切出来的矩形块就作为模型的输入，从mask上切出的矩形块用来制作GT，Split模型输出两个向量长度分别为矩形块的长和宽，以列为例，遍历所有列，如果当前列的所有行中存在1，则列向量的相应位置赋为1，否则赋为0，行向量就去遍历所有列，最终就可以得到需要的两个向量了。
对于Merge模型的GT是两个矩阵，向右合并矩阵`R`和向下合并矩阵`D`，同时模型的输入上加入了表格结构，需要制作这两类数据，从Split模型的GT中得到表格的横竖线的位置，比如行的向量为`[0,0,1,1,1,0,0,0,1,1,1,0,0,0]`,根据原论文中的做法，出现1的地方表示有线，线是有宽度的，令连续出现1的中心为线的位置，则线的位置为`[3,9]`，然后normalize`[0.21,0.64]`。这样就得到了表格的横线竖线的结构了。
求Merge模型的GT也就是那两个合并矩阵的方法，我的方法是根据表格结构，通过在mask上去计算相邻列在某一确定的行上之间的像素值的和与设定的阈值比较来判断这两列之间在这一行上是否有线也就是是否需要合并，举个例子来说，比如横线的位置还是`[3,9]`， 竖线的位置为`[2,5]`， 如果要判断两个横线间在竖线为2处是否存在线，则取mask中的相应区域并求和`np.sum(mask[3:9,2])`,  假如大于了设定的阈值，则在向右合并矩阵的相应位置设为1,`R[1,0] = 1`。按照这样的方法就可以制作好需要的数据了。

不知道这样描述你能否理解，因为不太清楚你们的数据标注方法，我所使用的脚本并不通用，你可以先自己尝试一下，如果有不清楚的地方可以再问我。

**Comment by ZF1546** [comment]
特别感谢你的详细讲解！谢谢！我先自己尝试一下，如果不行可能还要麻烦你，不好意思，感谢！

**Comment by ZF1546** [comment]
@solitaire2015 你好，打扰了，我尝试使用你给的方法，标注了一些数据集，但是效果很不理想。我想可能是我在哪个步骤误解了你的意思，导致数据集标注出现问题，不知道可否共享一下你们的数据集标注方法脚本，不胜感激！如果不方便也没关系，谢谢！

**Comment by solitaire2015** [comment]
@ZF1546 好的，等我下午整理一下。方便的话你也可以贴几张你们的样本。

**Comment by ZF1546** [comment]
@solitaire2015 你好，不好意思，有事情耽误了，麻烦你啦，下面是几张我们的样本图。
![20102171](https://user-images.githubusercontent.com/45488462/74630044-a7c5f700-5194-11ea-9faa-b2d08a2c86ef.png)
![20202172](https://user-images.githubusercontent.com/45488462/74630047-aa285100-5194-11ea-9df6-559f9f9f5d2a.png)
![2020-02-17 14-45-02屏幕截图](https://user-images.githubusercontent.com/45488462/74630087-c1673e80-5194-11ea-93db-88f423d09b7e.png)
![2020-02-17 14-45-31屏幕截图](https://user-images.githubusercontent.com/45488462/74630091-c2986b80-5194-11ea-8d98-e1dffa33ccc1.png)

**Comment by solitaire2015** [comment]
@ZF1546, 脚本整理好了，提交到了`data_utils` 目录下，你根据你们的label类型重写一下`extract_lines_from_xml` 这个方法应该就可以用了。
另外，我看到你们的数据有一些无线表格，这种要比有线的难一点，需要统一标注标准，根据原论文中的方法，无线的表格线标注时应当使线尽量宽，挨到两端的字。还可以增加模型的复杂度，多迭代几个blocks。

**Comment by ZF1546** [comment]
@solitaire2015 你好，非常感谢你的脚本整理及共享，你提出的无线表标注建议非常好，这个确实有问题，谢谢！非常感谢！

**Comment by ZF1546** [comment]
@solitaire2015 你好，你们标注是使用多边形标注吗？我们使用labelme矩形标注方法。如果方面的话可以贴几张你们的标注样本图吗？谢谢！

**Comment by solitaire2015** [comment]
我们也是标注的矩形。
![mask](https://user-images.githubusercontent.com/15261283/74640366-62acbf80-51aa-11ea-87c5-005fccbe97f3.png)
这是根据标注画出的mask。

**Comment by ZF1546** [comment]
@solitaire2015 好的，谢谢，看了你们的mask，你们的表格原图也很复杂，不知道你们是如何标注的，可否说一下。之前一些图片我们先是手动标注，太耽误时间了，接下来准备应用程序半自动打标，想到两个方案：一个是结合简单图表检测模型，检测表格横纵线位置信息，进行标注；二是结合pdf文件读取表格位置信息，生成标注，然后将pdf转图片。
对于这两个方案，希望能得到你的指点和建议，谢谢！

**Comment by solitaire2015** [comment]
我们的数据都是人工标注的，这两种方法也要具体看你们真实数据是怎么样的。如果能用pdf生成是最好，可以去看一下TableBank数据集，他们有详细的生成方法，如果真实数据都是图片，最好还是手动标注，不要让训练数据和真实的相差太多。

**Comment by ZF1546** [comment]
恩恩，好的，谢谢啦，特别感谢！

**Comment by solitaire2015** [comment]
@ZF1546 没事，客气了。

**Comment by ZF1546** [comment]
@solitaire2015 你好，打扰了，共享的模型是你们的最终模型吗，我这边训练输出的效果比较差，还需要继续训练，不确定其最终可行性如何，如果方便的话，可以共享你们的最终模型吗，谢谢！

**Comment by solitaire2015** [comment]
@ZF1546 是我们的最终模型了。效果不好具体的表现是什么呢？
