### ISSUE TITLE
推理模型问题

### ISSUE THREAD

**Issue by dongcaicheng** [solitaire2015/Split_Merge_table_recognition#5]
你好，我用百度网盘的split模型推理，输出结果可视化后有问题。请问网盘上的模型是否正确

**Comment by dongcaicheng** [comment]
![image](https://user-images.githubusercontent.com/35760496/78522003-74036700-77fe-11ea-8f2a-b2406bbebc68.png)
![Uploading image.png…]()

**Comment by dongcaicheng** [comment]
![image](https://user-images.githubusercontent.com/35760496/78522017-84b3dd00-77fe-11ea-9bed-96db7db78d96.png)
![image](https://user-images.githubusercontent.com/35760496/78522031-8b425480-77fe-11ea-8528-f043222dc30a.png)

**Comment by dongcaicheng** [comment]
上面是输入输出结果

**Comment by solitaire2015** [comment]
@dongcaicheng 请问你是怎么使用这个模型的呢，这个模型是在我们私有数据集上训练的，我之前尝试过在一些其他数据上的结果，不是很好。

**Comment by dongcaicheng** [comment]
我用代码里提供的图片和上面的图片分别试过，效果都不行。上面这张应该算简单场景了，应该能检测出来啊。

**Comment by solitaire2015** [comment]
这个是我测试的split结果，你看一下是不是通道的位置弄错了，之前我是channel first，今天测试的时候发现变成了channel last, 得到的结果就不对，调整一下通道就可以了。
![image](https://user-images.githubusercontent.com/15261283/78622085-c902b400-78b6-11ea-8bc8-e676aaa9265f.png)

**Comment by dongcaicheng** [comment]
我下载的模型输入要求是channel last的。我也是按channel last输入的。请问是不是模型有问题？您用百度网盘里的split_cp.pth试过吗。

**Comment by dongcaicheng** [comment]
![image](https://user-images.githubusercontent.com/35760496/78864839-1164d200-7a6f-11ea-8213-4043d5236a8d.png)
这是我的推理代码，由于没有label，dataset那部分修改了下。

**Comment by solitaire2015** [comment]
@dongcaicheng 我使用的是从百度盘里下载的模型，这个模型的输入需要channe first。
你试一下用这个方法得到模型输入，看看结果：
```
def img2tensor(img_pth, scale=0.5, min_width=40):
    img = Image.open(img_pth).convert('RGB')
    img = np.array(img)
    h, w, c = img.shape

    new_h = int(scale * h) if int(
      scale * h) > min_width else min_width
    new_w = int(scale * w) if int(
        scale * w) > min_width else min_width
    img = cv2.resize(img,(new_w, new_h), interpolation=cv2.INTER_AREA)
    img_tensor = torch.from_numpy(img/255.).type(torch.FloatTensor)
    img_tensor = img_tensor.permute(2,0,1)
    return img_tensor

**Comment by dongcaicheng** [comment]
![image](https://user-images.githubusercontent.com/35760496/78866693-7968e780-7a72-11ea-816d-2623e2ba9722.png)
![image](https://user-images.githubusercontent.com/35760496/78866715-81288c00-7a72-11ea-994e-5178ffe31788.png)
白色线条表示表格线，感觉结果还是不太正常吧。另外阈值一般选多大？0.5吗

**Comment by dongcaicheng** [comment]
![image](https://user-images.githubusercontent.com/35760496/78867187-47a45080-7a73-11ea-9a59-d6dcf53338cd.png)
![image](https://user-images.githubusercontent.com/35760496/78867195-4b37d780-7a73-11ea-9baa-8fa91aa069d3.png)
这是直接用split_input跑出的结果

**Comment by solitaire2015** [comment]
@dongcaicheng 还是正常的，这个模型是在私有数据上训练的，我之前也尝试过其他的一些表格图片，效果是不太好。还是要在自己的数据集上训练或者fine-tune。阈值一般设0.5就可以了。

**Comment by dongcaicheng** [comment]
请问这个模型不是ICDAR比赛的模型？不是的话能否提供下那个模型？

**Comment by solitaire2015** [comment]
@dongcaicheng 不是ICDAR数据集训练的模型，我也没有这个预训练的模型。抱歉。

**Comment by dongcaicheng** [comment]
好的，多谢哈
